name = "SequentialQuantileEstimator"
uuid = "a10d28a5-d1c8-4bef-92cc-d118ea2023a9"
authors = ["smallpondtom <tkoike45@gmail.com>"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Random = "1.11.0"
